
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftANDALERTA AND BOOL DESLIGAR DISPOSITIVO DOISPONTOS ENTAO ENVIAR EQUALS ID LBRACE LIGAR LPAR NUM OPLOGIC PARA PONTO RBRACE RPAR SE SENAO SET STRING TODOS VIRGULAprogram : devices cmdsdevices : device devicesdevices : devicedevice : DISPOSITIVO DOISPONTOS LBRACE ID RBRACE\n              | DISPOSITIVO DOISPONTOS LBRACE ID VIRGULA ID RBRACEcmds : command cmdscmds : commandcommand : cmd PONTOcmd : attrib\n           | obsact\n           | actattrib : SET ID EQUALS varvar : NUM\n           | BOOLobsact : SE obs ENTAO actobsact : SE obs ENTAO act SENAO actobs : obs_baseobs : obs_base AND obsobs_base : ID OPLOGIC varact : action IDact : ENVIAR ALERTA LPAR STRING RPAR IDact : ENVIAR ALERTA STRING IDact : ENVIAR ALERTA LPAR STRING VIRGULA ID RPAR IDact : ENVIAR ALERTA STRING VIRGULA ID IDact : ENVIAR ALERTA LPAR STRING VIRGULA ID RPAR PARA TODOS DOISPONTOS id_listact : ENVIAR ALERTA LPAR STRING RPAR PARA TODOS DOISPONTOS id_listaction : LIGAR\n              | DESLIGARid_list : ID VIRGULA id_listid_list : ID'
    
_lr_action_items = {'DISPOSITIVO':([0,3,44,56,],[4,4,-4,-5,]),'$end':([1,5,6,19,20,],[0,-1,-7,-6,-8,]),'SET':([2,3,6,17,20,44,56,],[11,-3,11,-2,-8,-4,-5,]),'SE':([2,3,6,17,20,44,56,],[12,-3,12,-2,-8,-4,-5,]),'ENVIAR':([2,3,6,17,20,29,44,46,56,],[14,-3,14,-2,-8,14,-4,14,-5,]),'LIGAR':([2,3,6,17,20,29,44,46,56,],[15,-3,15,-2,-8,15,-4,15,-5,]),'DESLIGAR':([2,3,6,17,20,29,44,46,56,],[16,-3,16,-2,-8,16,-4,16,-5,]),'DOISPONTOS':([4,57,64,],[18,59,66,]),'PONTO':([7,8,9,10,25,35,36,37,38,42,51,52,55,60,62,63,67,68,],[20,-9,-10,-11,-20,-12,-13,-14,-15,-22,-16,-21,-24,-23,-26,-30,-29,-25,]),'ID':([11,12,13,15,16,27,30,33,43,45,47,48,49,58,59,65,66,],[21,24,25,-27,-28,34,24,42,49,50,52,54,55,60,63,63,63,]),'ALERTA':([14,],[26,]),'LBRACE':([18,],[27,]),'EQUALS':([21,],[28,]),'ENTAO':([22,23,36,37,39,40,],[29,-17,-13,-14,-18,-19,]),'AND':([23,36,37,40,],[30,-13,-14,-19,]),'OPLOGIC':([24,],[31,]),'SENAO':([25,38,42,52,55,60,62,63,67,68,],[-20,46,-22,-21,-24,-23,-26,-30,-29,-25,]),'LPAR':([26,],[32,]),'STRING':([26,32,],[33,41,]),'NUM':([28,31,],[36,36,]),'BOOL':([28,31,],[37,37,]),'VIRGULA':([33,34,41,63,],[43,45,48,65,]),'RBRACE':([34,50,],[44,56,]),'RPAR':([41,54,],[47,58,]),'PARA':([47,58,],[53,61,]),'TODOS':([53,61,],[57,64,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'devices':([0,3,],[2,17,]),'device':([0,3,],[3,3,]),'cmds':([2,6,],[5,19,]),'command':([2,6,],[6,6,]),'cmd':([2,6,],[7,7,]),'attrib':([2,6,],[8,8,]),'obsact':([2,6,],[9,9,]),'act':([2,6,29,46,],[10,10,38,51,]),'action':([2,6,29,46,],[13,13,13,13,]),'obs':([12,30,],[22,39,]),'obs_base':([12,30,],[23,23,]),'var':([28,31,],[35,40,]),'id_list':([59,65,66,],[62,67,68,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> devices cmds','program',2,'p_program','compilador.py',87),
  ('devices -> device devices','devices',2,'p_devices_multiple','compilador.py',91),
  ('devices -> device','devices',1,'p_devices_single','compilador.py',95),
  ('device -> DISPOSITIVO DOISPONTOS LBRACE ID RBRACE','device',5,'p_device','compilador.py',99),
  ('device -> DISPOSITIVO DOISPONTOS LBRACE ID VIRGULA ID RBRACE','device',7,'p_device','compilador.py',100),
  ('cmds -> command cmds','cmds',2,'p_cmds_multiple','compilador.py',107),
  ('cmds -> command','cmds',1,'p_cmds_single','compilador.py',111),
  ('command -> cmd PONTO','command',2,'p_command','compilador.py',115),
  ('cmd -> attrib','cmd',1,'p_cmd','compilador.py',119),
  ('cmd -> obsact','cmd',1,'p_cmd','compilador.py',120),
  ('cmd -> act','cmd',1,'p_cmd','compilador.py',121),
  ('attrib -> SET ID EQUALS var','attrib',4,'p_attrib','compilador.py',125),
  ('var -> NUM','var',1,'p_var','compilador.py',129),
  ('var -> BOOL','var',1,'p_var','compilador.py',130),
  ('obsact -> SE obs ENTAO act','obsact',4,'p_obsact_if','compilador.py',134),
  ('obsact -> SE obs ENTAO act SENAO act','obsact',6,'p_obsact_if_else','compilador.py',138),
  ('obs -> obs_base','obs',1,'p_obs_single','compilador.py',142),
  ('obs -> obs_base AND obs','obs',3,'p_obs_and','compilador.py',146),
  ('obs_base -> ID OPLOGIC var','obs_base',3,'p_obs_base','compilador.py',150),
  ('act -> action ID','act',2,'p_act_basic','compilador.py',154),
  ('act -> ENVIAR ALERTA LPAR STRING RPAR ID','act',6,'p_act_alert_msg','compilador.py',158),
  ('act -> ENVIAR ALERTA STRING ID','act',4,'p_act_alert_msg_sem_paren','compilador.py',162),
  ('act -> ENVIAR ALERTA LPAR STRING VIRGULA ID RPAR ID','act',8,'p_act_alert_msg_obs','compilador.py',167),
  ('act -> ENVIAR ALERTA STRING VIRGULA ID ID','act',6,'p_act_alert_msg_obs_sem_paren','compilador.py',171),
  ('act -> ENVIAR ALERTA LPAR STRING VIRGULA ID RPAR PARA TODOS DOISPONTOS id_list','act',11,'p_act_alert_msg_obs_all','compilador.py',175),
  ('act -> ENVIAR ALERTA LPAR STRING RPAR PARA TODOS DOISPONTOS id_list','act',9,'p_act_broadcast','compilador.py',179),
  ('action -> LIGAR','action',1,'p_action','compilador.py',184),
  ('action -> DESLIGAR','action',1,'p_action','compilador.py',185),
  ('id_list -> ID VIRGULA id_list','id_list',3,'p_id_list_multiple','compilador.py',189),
  ('id_list -> ID','id_list',1,'p_id_list_single','compilador.py',193),
]
